parameters:
    uf.poll.voting.class: Userfriendly\Bundle\PollBundle\Poll\Voting

services:
    uf.poll.voting:
        class: '%uf.poll.voting.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%uf.poll.config%'
