#parameters:
#    uf.example.class:                       Userfriendly\Bundle\PollBundle\Example

#services:
#    uf.example:
#        class: %uf.example.class%
#        arguments:
#            - '@doctrine.orm.entity_manager'
